@startuml

title Product Model

class Product {
    -name:string
    -price:float
    -quantity:int 
    --
    +Product(name:string ,price:float, quantity:int)
    --
    +getName():stirng
    +getPrice():float
    +getQuantity():int
    --
    +setName(value):void
    +setPrice(value):void
    +setQuantity(value):void
    --
    +getTotalPrice():float
}

class Object{
    toString():string
}

Product -up-|> Object : "<<extends>>"

hide empty members

@enduml